<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefKlpSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::unprepared("
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '002', 'DEWAN PERWAKILAN RAKYAT', 'DPR', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '004', 'BADAN PEMERIKSA KEUANGAN', 'BPK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '006', 'KEJAKSAAN REPUBLIK INDONESIA', 'Kejaksaan RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '007', 'SEKRETARIAT NEGARA', 'Sekretariat Negara', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '010', 'KEMENTERIAN DALAM NEGERI', 'Kemendagri', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '011', 'KEMENTERIAN LUAR NEGERI', 'Kemlu RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '012', 'KEMENTERIAN PERTAHANAN', 'Kemhan RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '013', 'KEMENTERIAN HUKUM DAN HAK ASASI MANUSIA RI', 'Kemenkumham RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '015', 'KEMENTERIAN KEUANGAN', 'Kemenkeu', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '018', 'KEMENTERIAN PERTANIAN', 'Kementan', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '020', 'KEMENTERIAN ENERGI DAN SUMBER DAYA MINERAL', 'Kementerian ESDM RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, 'KHS', 'KEMENTERIAN PERHUBUNGAN SIMULASI', 'Kemenhub', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '023', 'KEMENTERIAN PENDIDIKAN DAN KEBUDAYAAN', 'Kemdikbudristek', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '024', 'KEMENTERIAN KESEHATAN', 'Kemenkes', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '025', 'KEMENTERIAN AGAMA', 'Kemenag', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '026', 'KEMENTERIAN KETENAGAKERJAAN', 'Kemnaker', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '027', 'KEMENTERIAN SOSIAL', 'Kemensos', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '029', 'KEMENTERIAN LINGKUNGAN HIDUP DAN KEHUTANAN', 'KLHK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '032', 'KEMENTERIAN KELAUTAN DAN PERIKANAN', 'KKP', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '033', 'KEMENTERIAN PEKERJAAN UMUM DAN PERUMAHAN RAKYAT', 'Kemen PUPR', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '034', 'KEMENTERIAN KOORDINATOR BIDANG POLITIK, HUKUM DAN KEAMANAN', 'Kemenko Polhukam', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '035', 'KEMENTERIAN KOORDINATOR BIDANG PEREKONOMIAN', 'Kemenko Perekonomian', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '036', 'KEMENTERIAN KOORDINATOR BIDANG PEMBANGUNAN MANUSIA DAN KEBUDAYAAN', 'Kemenko PMK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '040', 'KEMENTERIAN PARIWISATA DAN EKONOMI KREATIF/BADAN PARIWISATA DAN EKONOMI KREATIF', 'Kemenparekraf', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '041', 'KEMENTERIAN BADAN USAHA MILIK NEGARA', 'Kementerian BUMN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '042', 'KEMENTERIAN RISET DAN TEKNOLOGI/BADAN RISET DAN INOVASI NASIONAL (BRIN)', 'BRIN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '044', 'KEMENTERIAN KOPERASI DAN USAHA KECIL DAN MENENGAH', 'Kemenkop UKM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '047', 'KEMENTERIAN PEMBERDAYAAN PEREMPUAN DAN PERLINDUNGAN ANAK', 'Kemen PPPA', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '048', 'KEMENTERIAN PENDAYAGUNAAN APARATUR NEGARA DAN REFORMASI BIROKRASI', 'Kemenpan RB', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '050', 'BADAN INTELIJEN NEGARA', 'BIN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '051', 'BADAN SIBER DAN SANDI NEGARA', 'BSSN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '052', 'DEWAN KETAHANAN NASIONAL', 'Wantannas', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '054', 'BADAN PUSAT STATISTIK', 'BPS', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '055', 'BADAN PERENCANAAN PEMBANGUNAN NASIONAL / BAPPENAS', 'BAPPENAS', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '056', 'KEMENTERIAN AGRARIA DAN TATA RUANG/BPN', 'BPN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '057', 'PERPUSTAKAAN NASIONAL REPUBLIK INDONESIA', 'Perpusnas', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '059', 'KEMENTERIAN KOMUNIKASI DAN INFORMATIKA', 'Kemenkominfo', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '060', 'KEPOLISIAN NEGARA REPUBLIK INDONESIA', 'Polri', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '063', 'BADAN PENGAWAS OBAT DAN MAKANAN', 'BPOM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '064', 'LEMBAGA KETAHANAN NASIONAL', 'Lemhannas', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '065', 'BADAN KOORDINASI PENANAMAN MODAL', 'BKPM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '066', 'BADAN NARKOTIKA NASIONAL (BNN)', 'BNN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '067', 'KEMENTERIAN DESA, PEMBANGUNAN DAERAH TERTINGGAL DAN TRANSMIGRASI', 'Kemendes', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '068', 'BADAN KEPENDUDUKAN DAN KELUARGA BERENCANA NASIONAL (BKKBN)', 'BKKBN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '074', 'KOMISI NASIONAL HAK ASASI MANUSIA', 'Komnas HAM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '075', 'BADAN METEOROLOGI, KLIMATOLOGI DAN GEOFISIKA', 'BMKG', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '076', 'KOMISI PEMILIHAN UMUM', 'KPU', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '077', 'MAHKAMAH KONSTITUSI RI', 'MK RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '078', 'PUSAT PELAPORAN DAN ANALISIS TRANSAKSI KEUANGAN (PPATK)', 'PPATK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '079', 'LEMBAGA ILMU PENGETAHUAN INDONESIA (LIPI)', 'LIPI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '080', 'BADAN TENAGA NUKLIR NASIONAL (BATAN)', 'BATAN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '081', 'BADAN PENGKAJIAN DAN PENERAPAN TEKNOLOGI (BPPT)', 'BPPT', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '082', 'LEMBAGA PENERBANGAN DAN ANTARIKSA NASIONAL (LAPAN)', 'LAPAN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '083', 'BADAN INFORMASI GEOSPASIAL (BIG)', 'BIG', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '084', 'BADAN STANDARISASI NASIONAL (BSN)', 'BSN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '085', 'BADAN PENGAWAS TENAGA NUKLIR (BAPETEN)', 'BAPETEN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '086', 'LEMBAGA ADMINISTRASI NEGARA', 'LAN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '087', 'ARSIP NASIONAL REPUBLIK INDONESIA', 'ANRI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '088', 'BADAN KEPEGAWAIAN NEGARA', 'BPN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '089', 'BADAN PENGAWASAN KEUANGAN DAN PEMBANGUNAN (BPKP) -A', 'BPKP', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '090', 'KEMENTERIAN PERDAGANGAN', 'Kemendag', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '092', 'KEMENTERIAN PEMUDA DAN OLAHRAGA', 'Kemenpora RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '093', 'KOMISI PEMBERANTASAN KORUPSI (KPK)', 'KPK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '095', 'DEWAN PERWAKILAN DAERAH (DPD)', 'DPD', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '100', 'KOMISI YUDISIAL REPUBLIK INDONESIA', 'KY RI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '103', 'BADAN NASIONAL PENANGGULANGAN BENCANA (BNPB)', 'BNPB', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '104', 'BADAN PELINDUNGAN PEKERJA MIGRAN INDONESIA (BP2MI)', 'BP2MI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '105', 'BADAN PENANGGULANGAN LUMPUR SIDOARJO (BPLS)', 'BPLS', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '106', 'LEMBAGA KEBIJAKAN PENGADAAN BARANG/JASA PEMERINTAH (LKPP)', 'LKPP', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '107', 'BADAN SAR NASIONAL', 'Basarnas', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '108', 'KOMISI PENGAWAS PERSAINGAN USAHA (KPPU)', 'KPPU', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '109', 'BADAN PENGEMBANGAN WILAYAH SURAMADU (BPWS)', 'BPWS', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '110', 'OMBUDSMAN REPUBLIK INDONESIA', 'Ombudsman', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '111', 'BADAN NASIONAL PENGELOLA PERBATASAN (BNPP)', 'BNPP', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '112', 'BADAN PENGUSAHAAN KAWASAN PERDAGANGAN BEBAS DAN PELABUHAN BEBAS BATAM (BPKPB BATAM)', 'BPKPB BATAM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '113', 'BADAN NASIONAL PENANGGULANGAN TERORISME (BNPT)', 'BNPT', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '114', 'SEKRETARIAT KABINET', 'Sekretariat Kabinet', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '115', 'BADAN PENGAWAS PEMILIHAN UMUM', 'Bawaslu', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '116', 'LEMBAGA PENYIARAN PUBLIK RADIO REPUBLIK INDONESIA', 'LPP', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '117', 'TELEVISI REPUBLIK INDONESIA', 'TVRI', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '118', 'BADAN PENGUSAHAAN KAWASAN PERDAGANGAN BEBAS DAN PELABUHAN BEBAS SABANG (BPKPB SABANG)', 'BPKPB SABANG', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '119', 'BADAN KEAMANAN LAUT', 'Bakamla', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '120', 'KEMENTERIAN KOORDINATOR BIDANG KEMARITIMAN DAN INVESTASI', 'KEMENKOMARVES', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '121', 'BADAN EKONOMI KREATIF', 'BEKRAF ', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '666', 'BADAN RESTORASI GAMBUT', 'BRGM', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '999', 'BAGIAN ANGGARAN BENDAHARA UMUM NEGARA', 'BA BUN', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '123', 'LEMBAGA PERLINDUNGAN SAKSI DAN KORBAN', 'LPSK', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
            INSERT INTO ref_klps (`parent_id`, `parent_root_id`, `kode`, `nama`, `nama_pendek`, `jenis`, `level`, `attrs`, `is_active`, `pimpinan`, `jabatan_pimpinan`, `logo`, `no_telp`, `website`, `fax`, `alamat`, `created_by`, `created_by_name`, `updated_by`, `updated_by_name`, `created_at`, `updated_at`) VALUES (NULL, NULL, '001', 'MAJELIS PERMUSYAWARATAN RAKYAT (MPR)', 'MPR', 'KL', 'PUSAT', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'System', NULL, 'System', '2023-12-19 01:12:26', '2023-12-19 01:12:26');
        ");
    }
}
